export ZSH="/home/sonyahon/.oh-my-zsh"

ZSH_THEME="bureau"
COMPLETION_WAITING_DOTS="true"

plugins=(git node yarn npm docker)

source $ZSH/oh-my-zsh.sh
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

alias zshconfig="vim ~/.zshrc"
alias alacrittyconfig="vim ~/.config/alacritty/alacritty.yml"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
